### PR TITLE
fixed build details

### PR DESCRIPTION
**Pull request by gherlein**
modernized the build stuff 
- renamed configure.in to configure.ac
- added autogen.sh to force proper automake 
- changed the README to README.md 
- changed Makefile.in to allow README.md instead of README

### CODE REVIEW

**Comment by JohannesBuchner** [comment]
Thank you for the patch! You seem to know what you are doing :)
What environment are you using? Because the build files say "foreign" instead of "gnu" now? Will it build without running autogen/automake on the typical Linux (Ubuntu etc)?

Could we use RestructuredText for the README file instead of MarkDown (README.rst instead of README.md), please?

**Comment by gherlein** [comment]
I am running Ubuntu 14.04 and it would not build.  It was failing on automake since the files in github called for automake 1.11 and 14.04 is using 1.14.  Running autogen.sh regenerates the configure to match the system you are running on.

automake will fail if the README is not present - which is isn't if we make it .md or .rst.  To fix that you change it from "gnu" to "foreign" and automake works again.  That's why it reports that way.

Can you merge this?  Then I will send you another one using .rst instead of .md

**Comment by JohannesBuchner** [comment]
Then I am confused. What was the motivation to make the README md instead of plain text? 

I think if you push more commits to your master they will be added to this pull request.

**Comment by gherlein** [comment]
README is boring text.  No formatting.  

I'll try another push and see.

**Comment by gherlein** [comment]
Looks like it added it

**Comment by JohannesBuchner** [comment]
Would the autogen be more robust if we moved back to plain text? I mean the README is not extraordinarily complex.

PS: The # is superfluous.

**Comment by gherlein** [comment]
Don't know all the side effects of making it foreign instead of gnu so I backed that out.  WIll solve that another day.  Hoping to get the necessary build stuff merged.

**Comment by JohannesBuchner** [comment]
Thank you! Hope the software is useful to you.

**Pull request merged**
